export const API_CONFIG = {
  BASE_URL: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001',
  ENDPOINTS: {
    AUTH: '/auth',
  },
};

export const AUTH_ENDPOINTS = {
  REGISTER: `${API_CONFIG.ENDPOINTS.AUTH}/register`,
  VERIFY_EMAIL: `${API_CONFIG.ENDPOINTS.AUTH}/verify-email`,
  RESEND_VERIFICATION: `${API_CONFIG.ENDPOINTS.AUTH}/resend-verification`,
  FORGOT_PASSWORD: `${API_CONFIG.ENDPOINTS.AUTH}/forgot-password`,
  RESET_PASSWORD: `${API_CONFIG.ENDPOINTS.AUTH}/reset-password`,
  LOGIN: `${API_CONFIG.ENDPOINTS.AUTH}/login`,
  REFRESH: `${API_CONFIG.ENDPOINTS.AUTH}/refresh`,
  LOGOUT: `${API_CONFIG.ENDPOINTS.AUTH}/logout`,
  GOOGLE: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.AUTH}/google`,
  FACEBOOK: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.AUTH}/facebook`,
  PROFILE: `${API_CONFIG.ENDPOINTS.AUTH}/profile`,
};
